language: java
jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

install: true

jobs:
  include:
    - stage: Assemble
      script: ./gradlew assemble
    - stage: Analysis
      script: ./gradlew ktlint
    - stage: Unit Tests
      script: ./gradlew :result:test :repository:test
    - stage: GitHub Release
      script: echo "Deploying to GitHub releases..."
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        on:
          tags: true