language: java
jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

install: true

jobs:
  include:
    - stage: Build
      script: ./gradlew build
    - stage: Unit Tests
      script: ./gradlew test
    - stage: GitHub Release
      script: echo "Deploying to GitHub releases..."
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        on:
          tags: true